### ISSUE TITLE
Create a update user endpoint

### ISSUE THREAD

**Issue by kartikpuri99** [adityabisoi/REST-fetch#13] opened 2021-03-09 16:35 UTC
I am a participant of GSSOC'21 and want to work on this issue.So there are endpoints for fetch,create,delete user I want to create a endpoint for updating a specific user.Kindly assign this issue to me

**Comment by hrushikesh-git** [comment] 2021-03-10 19:25
@adityabisoi  hi I have following you on GitHub for 1 year really impressed by your work. Please assign me this issue I want to work on it as GSSOC'20 participant

**Comment by adityabisoi** [comment] 2021-03-11 07:09
@kartikpuri99 Please got through the documentation in detail to understand the use-case of the application. This is a REST API service which must provide placeholder and API testing capabilities. We cannot allow users to change the data through DELETE, UPDATE or PATCH requests. Closing the issue now.

**Comment by adityabisoi** [comment] 2021-03-11 07:10
@hrushikesh-git Thank you, since the issue is not in alignment with the scope of the application, please comment on a different issue. In case of any doubts, you can reach out to me, or mentors in the discord project server.

**Closed by adityabisoi** 2021-03-11 07:10 UTC
Labels: gssoc21
